name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Visual Studio
      uses: actions/setup-msbuild@v1
      
    - name: Install OpenSSL
      run: |
        choco install openssl
        echo "::add-path::C:\\Program Files\\OpenSSL-Win64\\bin"  # Add OpenSSL bin directory to PATH
        echo "::set-env name=OPENSSL_ROOT_DIR::C:\\Program Files\\OpenSSL-Win64"
        echo "::set-env name=OPENSSL_LIBRARIES::C:\\Program Files\\OpenSSL-Win64\\lib"

    - name: Build
      run: msbuild HMACtask/HMACtask.sln /p:Configuration=Release
