name: Build and Test C++ Project with Required OpenSSL Libraries

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install necessary OpenSSL libraries
      run: |
        choco install openssl.light

    - name: Set environment variables for OpenSSL
      run: |
        echo "OPENSSL_ROOT_DIR=C:\Program Files\OpenSSL-Win64" >> $GITHUB_ENV
        echo "OPENSSL_LIBRARIES=C:\Program Files\OpenSSL-Win64\lib" >> $GITHUB_ENV
        echo "INCLUDE=C:\Program Files\OpenSSL-Win64\include;%INCLUDE%" >> $GITHUB_ENV
        echo "LIB=C:\Program Files\OpenSSL-Win64\lib;%LIB%" >> $GITHUB_ENV

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build with MSBuild
      run: msbuild /p:Configuration=Release /p:Platform=x64 HMACtask/HMACtask.sln
