name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Set up Visual Studio
      uses: actions/setup-dotnet@v3
      with:
        vs-version: 2022

    - name: Build Solution
      run: |
        msbuild "../.././HMACtask/HMACtask.sln" /p:Configuration=Release

    - name: Run Tests
      run: |
        vstest.console.exe "../.././HMACtask/HMACtask.sln" /p:Configuration=Release
