name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Download OpenSSL
      run: |
        curl -L -o openssl.zip https://slproweb.com/download/Win64OpenSSL-1_1_1g.exe
        7z x openssl.zip -o"C:\OpenSSL"
    
    - name: Build Solution
      run: msbuild HMACtask/HMACtask.sln /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v142 /p:IncludePath="C:\OpenSSL\include" /p:LibraryPath="C:\OpenSSL\lib"
      
    - name: Run Tests
      run: vstest.console.exe HMACtask/HMACtask.sln /p:Configuration=Release

    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: latest.zip
        path: HMACtask/HMACtask.sln

    - name: Sign release
      run: |
        echo $PRIVATE_KEY > privatekey.pem
        openssl dgst -sha512 -sign privatekey.pem -out latest.sig latest.zip
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
