name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install OpenCV dependencies
      run: |
        choco install opencv -y
        Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build Solution
      run: |
        msbuild HMACtask/HMACtask.sln /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v142

    - name: Run Tests
      run: |
        vstest.console.exe HMACtask/HMACtask.sln /p:Configuration=Release
