name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install OpenCV dependencies
      run: |
        curl -OL https://github.com/opencv/opencv/releases/download/4.9.0/opencv-4.9.0-vc16-vc14-win64.exe
        .\opencv-4.9.0-vc16-vc14-win64.exe /verysilent /norestart
        del .\opencv-4.9.0-vc16-vc14-win64.exe

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build Solution
      run: msbuild HMACtask/HMACtask.sln /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v142

    - name: Run Tests
      run: vstest.console.exe HMACtask/HMACtask.sln /p:Configuration=Release
