name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Install OpenSSL
      run: |
        choco install openssl
        setx PATH "%PATH%;C:\Program Files\OpenSSL-Win64\bin"
        setx INCLUDE "%INCLUDE%;C:\Program Files\OpenSSL-Win64\include"
        setx LIB "%LIB%;C:\Program Files\OpenSSL-Win64\lib"
    
    - name: Build Solution
      run: msbuild HMACtask/HMACtask.sln /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v142

    - name: Run Tests
      run: vstest.console.exe HMACtask/HMACtask.sln /p:Configuration=Release

    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: latest.zip
        path: HMACtask/HMACtask.sln

    - name: Sign release
      run: |
        echo $PRIVATE_KEY > privatekey.pem
        openssl dgst -sha512 -sign privatekey.pem -out latest.sig latest.zip
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
