name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up MSVC environment
      uses: microsoft/setup-msvc@v1.8.2

    - name: Install OpenSSL
      run: |
        choco install openssl
        refreshenv

    - name: Install OpenCV dependencies
      run: |
        choco install opencv

    - name: Build HMACtask
      run: |
        msbuild HMACtask/HMACtask.sln /p:Configuration=Debug

    - name: Test HMACtask
      run: |
        cd HMACtask
        ./Debug/HMACtask.exe  # Assuming Debug configuration
