name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install MSVC
      run: |
        choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"

    - name: Install OpenSSL
      run: |
        choco install openssl
        refreshenv

    - name: Install OpenCV dependencies
      run: |
        choco install opencv

    - name: Build HMACtask
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
        msbuild HMACtask/HMACtask.sln /p:Configuration=Debug

    - name: Test HMACtask
      run: |
        cd HMACtask
        ./Debug/HMACtask.exe  # Assuming Debug configuration
