name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      OPENSSL_PATH: "C:\\Program Files\\OpenSSL\\bin"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install MSVC
      run: |
        choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.Windows10SDK.18362"

    - name: Install OpenSSL
      run: |
        choco install openssl
        echo "OPENSSL_PATH=${OPENSSL_PATH}" >> $GITHUB_ENV

    - name: Install OpenCV dependencies
      run: |
        choco install opencv

    - name: Add OpenSSL to PATH
      run: |
        $newPath = "${env:OPENSSL_PATH};${env:Path}"
        [Environment]::SetEnvironmentVariable("Path", $newPath, "Machine")

    - name: Set up MSBuild environment and build
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
        set PATH=%ProgramFiles(x86)%\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin;%PATH%
        where msbuild
        msbuild HMACtask\HMACtask.sln /p:Configuration=Debug

    - name: Test HMACtask
      shell: cmd
      run: |
        cd HMACtask
        .\Debug\HMACtask.exe  # Assuming Debug configuration
